### ISSUE TITLE
List performances of a Show fails

### ISSUE THREAD

**Issue by soumyakcherian** [dormouse88/theatre#8]
@dormouse88 
Steps
1. Start the application 
2. Enter Menu number 5
3. Enter 1
![image](https://user-images.githubusercontent.com/108669311/179198262-f7b8ee80-274d-48c9-bbec-03f67fc04f49.png)

This issue doesn't occur after browsing Shows using the Menu option 1 and then Menu 5

**Comment by dormouse88** [comment]
Good catch
