### ISSUE TITLE
View Show Details issue

### ISSUE THREAD

**Issue by soumyakcherian** [dormouse88/theatre#9]
@dormouse88 

Similar issue on option 4

Steps
 1. Start application
 2. Select Menu 4
 3. Enter value 1
 
![image](https://user-images.githubusercontent.com/108669311/179209668-c979ccbf-493a-4f41-b257-ee956dea5cdd.png)
The issue doesn't occur when selecting Menu 1 and then Menu 4 then Type in 1

**Comment by dormouse88** [comment]
That's intended behaviour.
Option 4 is for checking the details of a show that has come up in a previous search, Until the user makes a search, they have no show to ask for details about.
